name: 'open-koqis'

services:
  open-koqis.api:
    image: open-koqis.api
    container_name: open-koqis.api
    ports:
      - "8080:8080" # HTTP
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: "Development"
        PORT: 8080
    depends_on:
      - open-koqis.mongo
      - open-koqis.mosquitto
      - open-koqis.otel-collector
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    restart: no
    volumes:
      # Hot reload for development
      - ./src/OpenKoqis.Api/appsettings.Development.json:/app/appsettings.Development.json:ro
      - ./src/OpenKoqis.Api/.env:/app/.env:ro

  open-koqis.mongo:
    image: mongo:8.2
    container_name: open-koqis.mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
  
  open-koqis.mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: open-koqis.mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto/config:/mosquitto/config
      - ./config/mosquitto/logs:/mosquitto/logs
      - ./config/mosquitto/data:/mosquitto/data
    restart: unless-stopped
    
  open-koqis.otel-collector:
    image: otel/opentelemetry-collector:0.140.0
    container_name: open-koqis.otel-collector
    command: [ "--config=/etc/otel-collector-config.yml" ]
    environment:
      SEQ_API_KEY: $SEQ_API_KEY
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yml:ro
    ports:
      - "1777:1777" # pprof (for debug)
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
      - "13133:13133" # Health checks
    depends_on:
      - open-koqis.seq
    restart: unless-stopped

  open-koqis.grafana:
    image: grafana/grafana:12.1
    container_name: open-koqis.grafana
    environment:
      GF_SECURITY_ADMIN_USER: $GRAFANA_USERNAME
      GF_SECURITY_ADMIN_PASSWORD: $GRAFANA_PASSWORD
    ports:
      - "3030:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  open-koqis.prometheus:
    image: prom/prometheus:v3.7.3
    container_name: open-koqis.prometheus
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command: [ "--config.file=/etc/prometheus/prometheus.yaml", "--storage.tsdb.retention.time=45d", "--storage.tsdb.retention.size=15GB" ]
    depends_on:
      - open-koqis.otel-collector
    restart: unless-stopped
    
  open-koqis.seq:
    image: datalust/seq:2025.2
    container_name: open-koqis.seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: $SEQ_FIRSTRUN_ADMINPASSWORD
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    restart: unless-stopped
    
networks:
  open-koqis_network:
    external: true
    
volumes:
  mongodb_data:
    driver: local
  grafana_data:
    driver: local
  prometheus_data:
    driver: local
  seq_data:
    driver: local